### ISSUE TITLE
Flexmock of staticmethods not torn down properly

### ISSUE THREAD

**Issue by afoglia** [flexmock/flexmock#31] opened 2019-10-11 01:18 UTC
If one tries to flexmock a staticmethod, after teardown, the staticmethod is no longer usable.

    >>> from __future__ import print_function
    >>> class Foo(object):
    ...   @staticmethod
    ...   def bar(x):
    ...     print("In Foo.bar")
    ... 
    >>> import flexmock
    >>> flexmock.__version__
    '0.10.4'
    >>> flexmock.flexmock(Foo).should_receive("bar").with_args(10).once()
    <flexmock.Expectation object at 0x7f69b23eaa10>
    >>> foo = Foo()
    >>> foo.bar(10)
    >>> flexmock.flexmock_teardown()
    >>> foo2 = Foo()
    >>> foo2.bar(5)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: 'staticmethod' object is not callable
    >>> foo.bar(10)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: 'staticmethod' object is not callable
    >>> Foo.bar(10)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: 'staticmethod' object is not callable

Somehow flexmock is messing with the descriptor protocol.

**Comment by afoglia** [comment] 2019-10-24 16:03
Here's a test showing it. It's identical to the test above it, but uses new-style classes, not old-style classes.

https://github.com/afoglia/flexmock/commit/641fde9ad5f81e191c2ef9350cf1b92e4f4a5e28

**Comment by afoglia** [comment] 2019-10-24 17:41
I sent a pull request. The problem comes down to the check in teardown at line https://github.com/bkabrda/flexmock/blob/master/flexmock.py#L665. There's a comment there implying the true-clause is only for pypy, but I don't know the history of it, or why it isn't checking if the implementation if pypy directly.

**Comment by ollipa** [comment] 2021-08-15 15:13
I can't reproduce this anymore with the latest development version so I'll close this. It seems that this was just an issue with Python 2 and support for Python 2 has been removed in the upcoming release.

**Closed as completed by ollipa** 2021-08-15 15:13 UTC
Labels: bug
