### ISSUE TITLE
Python 3 regression in 0.10.0?

### ISSUE THREAD

**Issue by obestwalter** [flexmock/flexmock#11] opened 2015-12-15 15:03 UTC
our CI borks, when tox is trying to install flexmock 0.10.0. I tried to reproduce it locally but there everything works fine. For now I pinned the version 0.9.7 but would be interested to know if others experienced the same problem.

```
Collecting flexmock
  Using cached [...]pypi/+f/92f/f94c9b7e70521/flexmock-0.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-d026h74v/flexmock/setup.py", line 15, in <module>
        long_description=open('README.md').read(),
      File "/tmp/bamboo-build/[...]/.tox/py34-linux-unittests/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 805: ordinal not in range(128)
```

**Comment by bkabrda** [comment] 2015-12-17 08:23
Thanks for the report, I'll look into it. The `ascii` codec problems usually occur when `LANG` env variable is set to something like `C`, thus Python 3 assumes that `ascii` is the current encoding. I'll try to see if this is the case.

**Comment by bkabrda** [comment] 2015-12-17 08:27
Ok, so I think I was right about the cause and fixed it in https://github.com/bkabrda/flexmock/commit/b5f5c92cfa4e84e48eca6014d874e71224d1ba70 - is it possible for you to confirm that the fix works in your environment, so that I can release new version?

**Comment by david-geiger** [comment] 2015-12-17 09:14
Hi,

I encountered the same build issue in our Mageia build system and so I can confirm that the commit b5f5c92 fixes now this issue for python 3 build.

before:
http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20151217082745.daviddavid.valstar.18499/log/python-flexmock-0.10.0-1.mga6/build.0.20151217082802.log

After:
http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20151217090346.daviddavid.valstar.21106/python-flexmock-0.10.0-1.mga6/build.0.20151217090402.log

Regards,
David

**Comment by bkabrda** [comment] 2015-12-17 09:45
Ok, thanks for letting me know. I'll release 0.10.1 in a couple of moments and then I'll close this bug.

**Comment by bkabrda** [comment] 2015-12-17 09:55
Released here: https://pypi.python.org/pypi/flexmock/0.10.1 enjoy!
If you see any more problems, please let me know.

**Closed as completed by bkabrda** 2015-12-17 09:55 UTC
Labels: bug

**Comment by obestwalter** [comment] 2015-12-17 12:17
@bkabrda Wow thanks, problem fixed and I learned something new about Python3 :)

**Comment by bkabrda** [comment] 2015-12-17 17:52
You're welcome! BTW this is not caused just by `LANG` env variable, it's more like `LC_ALL` > `LC_CTYPE` > `LANG` > `LANGUAGE` (">" == "is more important than"). It's documented as part of `locale.getdefaultlocale()`: https://docs.python.org/3.5/library/locale.html#locale.getdefaultlocale
